#!/usr/bin/env python3
"""Plot the confusion matrix and ACETs for YOLOv7.  All data was copied
verbatim from the confusion matrices generated by YOLOv7's training."""


import numpy as np
from matplotlib import pyplot as plt


CLASSES = ['Duckie', 'Duckiebot', 'Cone', 'Background']


def add_text(data: np.ndarray, row: int, column: int) -> None:
    """Add text to a heat map and automatically color it such that text in
    lighter squares is colored black and text in darker squares is colored
    white.

    Args:
        data - confusion matrix data
        row - subplot's row
        column - subplot's column
    """
    for i in range(len(CLASSES)):
        for j in range(len(CLASSES)):
            axs[row, column].text(
                j,
                i,
                data[i, j],
                ha='center',
                va='center',
                color='w' if data[i, j] > 0.5 else 'k'
            )


if __name__ == '__main__':
    # Initialize plot
    fig, axs = plt.subplots(2, 2)

    # 64x64
    yolo64 = np.array(
        [
            [0.00, 0.00, 0.00, 0.00],
            [0.00, 0.00, 0.00, 0.00],
            [0.00, 0.00, 0.00, 1.00],
            [1.00, 1.00, 1.00, 0.00]
        ]
    )
    axs[0, 0].imshow(yolo64, cmap="YlGn")
    axs[0, 0].set_xticks(np.arange(len(CLASSES)), labels=CLASSES)
    axs[0, 0].set_yticks(np.arange(len(CLASSES)), labels=CLASSES)
    add_text(yolo64, 0, 0)
    axs[0, 0].set_title("64x64 (ACET: 99.0 ms)")

    # 96x96
    yolo96 = np.array(
        [
            [0.00, 0.00, 0.00, 0.00],
            [0.00, 0.00, 0.00, 0.00],
            [0.00, 0.00, 0.76, 1.00],
            [1.00, 1.00, 0.24, 0.00]
        ]
    )
    axs[0, 1].imshow(yolo96, cmap="YlGn")
    axs[0, 1].set_xticks(np.arange(len(classes)), labels=classes)
    axs[0, 1].set_yticks(np.arange(len(classes)), labels=classes)
    add_text(yolo96, 0, 1)
    axs[0, 1].set_title("96x96 (ACET: 119.5 ms)")

    # 128x128
    yolo128 = np.array(
        [
            [0.36, 0.00, 0.00, 0.05],
            [0.00, 0.41, 0.00, 0.81],
            [0.00, 0.00, 0.91, 0.15],
            [0.63, 0.59, 0.09, 0.00]
        ]
    )
    axs[1, 0].imshow(yolo128, cmap="YlGn")
    axs[1, 0].set_xticks(np.arange(len(CLASSES)), labels=CLASSES)
    axs[1, 0].set_yticks(np.arange(len(CLASSES)), labels=CLASSES)
    add_text(yolo128, 1, 0)
    axs[1, 0].set_title("128x128 (ACET: 129.5 ms)")

    # 160x160
    yolo160 = np.array(
        [
            [0.49, 0.00, 0.00, 0.05],
            [0.00, 0.65, 0.00, 0.79],
            [0.00, 0.00, 0.94, 0.16],
            [0.51, 0.35, 0.06, 0.00]
        ]
    )
    axs[1, 1].imshow(yolo160, cmap="YlGn")
    axs[1, 1].set_xticks(np.arange(len(CLASSES)), labels=CLASSES)
    axs[1, 1].set_yticks(np.arange(len(CLASSES)), labels=CLASSES)
    add_text(yolo160, 1, 1)
    axs[1, 1].set_title("160x160 (ACET: 163.4 ms)")

    # Plot
    fig.tight_layout()
    plt.show()

